ALTER TABLE anime
ALTER COLUMN start_date DATETIME;

ALTER TABLE anime
ALTER COLUMN end_date DATETIME;

ALTER TABLE game
ALTER COLUMN start_date DATETIME;

ALTER TABLE game
ALTER COLUMN end_date DATETIME;

ALTER TABLE manga
ALTER COLUMN start_date DATETIME;

ALTER TABLE manga
ALTER COLUMN end_date DATETIME;